name = "posix_tools_du"
description = "du command for posix_tools"
version = "0.1.0"
authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]
licenses = "MIT"
executables = ["du"]
project-files = ["posix_tools_du.gpr"]

[[depends-on]]
posix_tools_common = "*"

[[pins]]
posix_tools_common = { path = "../../common" }

[build-profiles]
"*" = "development"
