with AUnit.Test_Fixtures;

package Command_Tests is
   type Fixture is new AUnit.Test_Fixtures.Test_Fixture with null record;

   procedure Test_Basename (T : in out Fixture);
   procedure Test_Basename_Edge_Cases (T : in out Fixture);
   procedure Test_Cat_Files (T : in out Fixture);
   procedure Test_Cat_Continues_After_Missing_File (T : in out Fixture);
   procedure Test_Cat_Standard_Input (T : in out Fixture);
   procedure Test_Cat_Byte_Preservation_Property (T : in out Fixture);
   procedure Test_Cat_Output_Failure (T : in out Fixture);
   procedure Test_Dirname (T : in out Fixture);
   procedure Test_Dirname_Edge_Cases (T : in out Fixture);
   procedure Test_Simple_Output_Failures (T : in out Fixture);
   procedure Test_Echo (T : in out Fixture);
   procedure Test_Echo_Data_Edge_Cases (T : in out Fixture);
   procedure Test_Echo_Extensions_Are_Sole_Argument (T : in out Fixture);
   procedure Test_End_Of_Options (T : in out Fixture);
   procedure Test_False (T : in out Fixture);
   procedure Test_False_Extension_Edges (T : in out Fixture);
   procedure Test_Head_Counts (T : in out Fixture);
   procedure Test_Head_Default_Limits (T : in out Fixture);
   procedure Test_Head_Prefix_Property (T : in out Fixture);
   procedure Test_Head_Invalid_Count (T : in out Fixture);
   procedure Test_Head_Multiple_File_Headers (T : in out Fixture);
   procedure Test_Head_Standard_Input (T : in out Fixture);
   procedure Test_Head_Output_Failure (T : in out Fixture);
   procedure Test_Help_And_Version (T : in out Fixture);
   procedure Test_Help_Locales (T : in out Fixture);
   procedure Test_Diagnostic_Locales (T : in out Fixture);
   procedure Test_Presentation_Styling (T : in out Fixture);
   procedure Test_Identity (T : in out Fixture);
   procedure Test_Pwd_Context_Fallbacks (T : in out Fixture);
   procedure Test_Pwd_Options (T : in out Fixture);
   procedure Test_Root_List (T : in out Fixture);
   procedure Test_Root_Usage_Edges (T : in out Fixture);
   procedure Test_Root_Paths (T : in out Fixture);
   procedure Test_Root_Verify (T : in out Fixture);
   procedure Test_Root_Command_Help_Uses_Command_Metadata (T : in out Fixture);
   procedure Test_Root_Version_And_Help (T : in out Fixture);
   procedure Test_Root_Localized_Help (T : in out Fixture);
   procedure Test_Root_Output_Failure (T : in out Fixture);
   procedure Test_Tail_Byte_Mode_Edges (T : in out Fixture);
   procedure Test_Tail_Compact_Counts (T : in out Fixture);
   procedure Test_Tail_Invalid_Count (T : in out Fixture);
   procedure Test_Tail_Line_Mode_Edges (T : in out Fixture);
   procedure Test_Tail_Multiple_File_Headers (T : in out Fixture);
   procedure Test_Tail_Plus_Origin (T : in out Fixture);
   procedure Test_Tail_Standard_Input (T : in out Fixture);
   procedure Test_Tail_Output_Failure (T : in out Fixture);
   procedure Test_Tail_Byte_Suffix_Property (T : in out Fixture);
   procedure Test_Usage_Errors (T : in out Fixture);
   procedure Test_True (T : in out Fixture);
   procedure Test_True_Extension_Edges (T : in out Fixture);
   procedure Test_Wc_Text_Counts (T : in out Fixture);
   procedure Test_Wc_Default_And_Mixed_Text (T : in out Fixture);
   procedure Test_Wc_Text_Invalid_UTF_8 (T : in out Fixture);
   procedure Test_Wc_Text_Malformed_UTF_8 (T : in out Fixture);
   procedure Test_Wc_Multiple_Files (T : in out Fixture);
   procedure Test_Wc_Standard_Input (T : in out Fixture);
   procedure Test_Wc_Byte_Count_Property (T : in out Fixture);
   procedure Test_Wc_Output_Failure (T : in out Fixture);
end Command_Tests;
