with Posix_Tools.Commands.Arch;
with Posix_Tools.Commands.Chgrp;
with Posix_Tools.Commands.Chmod;
with Posix_Tools.Commands.Chown;
with Posix_Tools.Commands.Cksum;
with Posix_Tools.Commands.Cmp;
with Posix_Tools.Commands.Comm;
with Posix_Tools.Commands.Cp;
with Posix_Tools.Commands.Cut;
with Posix_Tools.Commands.Date;
with Posix_Tools.Commands.Dd;
with Posix_Tools.Commands.Df;
with Posix_Tools.Commands.Du;
with Posix_Tools.Commands.Env;
with Posix_Tools.Commands.Expand;
with Posix_Tools.Commands.Expr;
with Posix_Tools.Commands.File;
with Posix_Tools.Commands.Find;
with Posix_Tools.Commands.Getconf;
with Posix_Tools.Commands.Fold;
with Posix_Tools.Commands.Groups;
with Posix_Tools.Commands.Hostname;
with Posix_Tools.Commands.Helpers;
with Posix_Tools.Commands.Id;
with Posix_Tools.Commands.Kill;
with Posix_Tools.Commands.Link;
with Posix_Tools.Commands.Ln;
with Posix_Tools.Commands.Locale;
with Posix_Tools.Commands.Logname;
with Posix_Tools.Commands.Ls;
with Posix_Tools.Commands.Mkdir;
with Posix_Tools.Commands.Mv;
with Posix_Tools.Commands.Mkfifo;
with Posix_Tools.Commands.Nice;
with Posix_Tools.Commands.Nl;
with Posix_Tools.Commands.Nohup;
with Posix_Tools.Commands.Od;
with Posix_Tools.Commands.Paste;
with Posix_Tools.Commands.Pathchk;
with Posix_Tools.Commands.Printenv;
with Posix_Tools.Commands.Printf;
with Posix_Tools.Commands.Readlink;
with Posix_Tools.Commands.Realpath;
with Posix_Tools.Commands.Rm;
with Posix_Tools.Commands.Rmdir;
with Posix_Tools.Commands.Seq;
with Posix_Tools.Commands.Sha256sum;
with Posix_Tools.Commands.Sleep;
with Posix_Tools.Commands.Split;
with Posix_Tools.Commands.Sort;
with Posix_Tools.Commands.Stat;
with Posix_Tools.Commands.Tee;
with Posix_Tools.Commands.Test_Command;
with Posix_Tools.Commands.Timeout;
with Posix_Tools.Commands.Tr;
with Posix_Tools.Commands.Touch;
with Posix_Tools.Commands.Tty;
with Posix_Tools.Commands.Uname;
with Posix_Tools.Commands.Uniq;
with Posix_Tools.Commands.Unexpand;
with Posix_Tools.Commands.Unlink;
with Posix_Tools.Commands.Which;
with Posix_Tools.Commands.Whoami;
with Posix_Tools.Commands.Xargs;
with Posix_Tools.Commands.Yes;

package body Posix_Tools.Commands.Dispatcher is
   procedure Run
     (Command : Dispatch_Command;
      Context : in out Posix_Tools.Commands.Contexts.Context'Class;
      Result  : out Posix_Tools.Commands.Results.Result)
   is
   begin
      if Posix_Tools.Commands.Helpers.Intercept_Extension (Context, Result) then
         return;
      end if;

      case Command is
         when Arch_Command => Posix_Tools.Commands.Arch.Run (Context, Result);
         when Chgrp_Command => Posix_Tools.Commands.Chgrp.Run (Context, Result);
         when Chmod_Command => Posix_Tools.Commands.Chmod.Run (Context, Result);
         when Chown_Command => Posix_Tools.Commands.Chown.Run (Context, Result);
         when Cksum_Command => Posix_Tools.Commands.Cksum.Run (Context, Result);
         when Cmp_Command => Posix_Tools.Commands.Cmp.Run (Context, Result);
         when Comm_Command => Posix_Tools.Commands.Comm.Run (Context, Result);
         when Cp_Command => Posix_Tools.Commands.Cp.Run (Context, Result);
         when Cut_Command => Posix_Tools.Commands.Cut.Run (Context, Result);
         when Date_Command => Posix_Tools.Commands.Date.Run (Context, Result);
         when Dd_Command => Posix_Tools.Commands.Dd.Run (Context, Result);
         when Df_Command => Posix_Tools.Commands.Df.Run (Context, Result);
         when Du_Command => Posix_Tools.Commands.Du.Run (Context, Result);
         when Env_Command => Posix_Tools.Commands.Env.Run (Context, Result);
         when Expand_Command => Posix_Tools.Commands.Expand.Run (Context, Result);
         when Expr_Command => Posix_Tools.Commands.Expr.Run (Context, Result);
         when File_Command => Posix_Tools.Commands.File.Run (Context, Result);
         when Find_Command => Posix_Tools.Commands.Find.Run (Context, Result);
         when Fold_Command => Posix_Tools.Commands.Fold.Run (Context, Result);
         when Getconf_Command => Posix_Tools.Commands.Getconf.Run (Context, Result);
         when Groups_Command => Posix_Tools.Commands.Groups.Run (Context, Result);
         when Hostname_Command => Posix_Tools.Commands.Hostname.Run (Context, Result);
         when Id_Command => Posix_Tools.Commands.Id.Run (Context, Result);
         when Kill_Command => Posix_Tools.Commands.Kill.Run (Context, Result);
         when Link_Command => Posix_Tools.Commands.Link.Run (Context, Result);
         when Ln_Command => Posix_Tools.Commands.Ln.Run (Context, Result);
         when Locale_Command => Posix_Tools.Commands.Locale.Run (Context, Result);
         when Logname_Command => Posix_Tools.Commands.Logname.Run (Context, Result);
         when Ls_Command => Posix_Tools.Commands.Ls.Run (Context, Result);
         when Mkdir_Command => Posix_Tools.Commands.Mkdir.Run (Context, Result);
         when Mkfifo_Command => Posix_Tools.Commands.Mkfifo.Run (Context, Result);
         when Mv_Command => Posix_Tools.Commands.Mv.Run (Context, Result);
         when Nice_Command => Posix_Tools.Commands.Nice.Run (Context, Result);
         when Nl_Command => Posix_Tools.Commands.Nl.Run (Context, Result);
         when Nohup_Command => Posix_Tools.Commands.Nohup.Run (Context, Result);
         when Od_Command => Posix_Tools.Commands.Od.Run (Context, Result);
         when Paste_Command => Posix_Tools.Commands.Paste.Run (Context, Result);
         when Pathchk_Command => Posix_Tools.Commands.Pathchk.Run (Context, Result);
         when Printenv_Command => Posix_Tools.Commands.Printenv.Run (Context, Result);
         when Printf_Command => Posix_Tools.Commands.Printf.Run (Context, Result);
         when Readlink_Command => Posix_Tools.Commands.Readlink.Run (Context, Result);
         when Realpath_Command => Posix_Tools.Commands.Realpath.Run (Context, Result);
         when Rm_Command => Posix_Tools.Commands.Rm.Run (Context, Result);
         when Rmdir_Command => Posix_Tools.Commands.Rmdir.Run (Context, Result);
         when Seq_Command => Posix_Tools.Commands.Seq.Run (Context, Result);
         when Sha256sum_Command => Posix_Tools.Commands.Sha256sum.Run (Context, Result);
         when Sleep_Command => Posix_Tools.Commands.Sleep.Run (Context, Result);
         when Split_Command => Posix_Tools.Commands.Split.Run (Context, Result);
         when Sort_Command => Posix_Tools.Commands.Sort.Run (Context, Result);
         when Stat_Command => Posix_Tools.Commands.Stat.Run (Context, Result);
         when Tee_Command => Posix_Tools.Commands.Tee.Run (Context, Result);
         when Test_Command => Posix_Tools.Commands.Test_Command.Run (Context, Result);
         when Timeout_Command => Posix_Tools.Commands.Timeout.Run (Context, Result);
         when Touch_Command => Posix_Tools.Commands.Touch.Run (Context, Result);
         when Tr_Command => Posix_Tools.Commands.Tr.Run (Context, Result);
         when Tty_Command => Posix_Tools.Commands.Tty.Run (Context, Result);
         when Unexpand_Command => Posix_Tools.Commands.Unexpand.Run (Context, Result);
         when Unlink_Command => Posix_Tools.Commands.Unlink.Run (Context, Result);
         when Uname_Command => Posix_Tools.Commands.Uname.Run (Context, Result);
         when Uniq_Command => Posix_Tools.Commands.Uniq.Run (Context, Result);
         when Which_Command => Posix_Tools.Commands.Which.Run (Context, Result);
         when Whoami_Command => Posix_Tools.Commands.Whoami.Run (Context, Result);
         when Xargs_Command => Posix_Tools.Commands.Xargs.Run (Context, Result);
         when Yes_Command => Posix_Tools.Commands.Yes.Run (Context, Result);
      end case;
   end Run;
end Posix_Tools.Commands.Dispatcher;
